[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle direct access to /api routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next_api/:splat"
  status = 200
  force = true

# Force trailing slash for consistent routing
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200
  force = true 