[build]
  command = "./netlify-build.sh"
  publish = "out"

[build.environment]
  NETLIFY_USE_YARN = "false"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 